/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iStarNftSol from "./IStarNft.sol";
export type { iStarNftSol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
